// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjR1LLHlJYMpMm_Wzan5idHSoiyHbpJs',
    appId: '1:856037366349:web:a78d9d66db766f0426da04',
    messagingSenderId: '856037366349',
    projectId: 'notification-53aa3',
    authDomain: 'notification-53aa3.firebaseapp.com',
    storageBucket: 'notification-53aa3.firebasestorage.app',
    measurementId: 'G-6PSHH60QG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeCJXtOECn1NXei12ewJLyyZyR-maL_5k',
    appId: '1:856037366349:android:4b1c45d5f7bf6a5a26da04',
    messagingSenderId: '856037366349',
    projectId: 'notification-53aa3',
    storageBucket: 'notification-53aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0lfzK6THAIbEvPIOaPVCrboicshjG2I',
    appId: '1:856037366349:ios:4440bbfbb5bb637326da04',
    messagingSenderId: '856037366349',
    projectId: 'notification-53aa3',
    storageBucket: 'notification-53aa3.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsFirebaseFlutter',
  );
}
